# Generated by Django 5.2.1 on 2025-05-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_creditcard_cvv_creditcard_card_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
