# Generated by Django 5.2.1 on 2025-05-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.CharField(max_length=7),
        ),
    ]
